### ISSUE TITLE
Export validation schema as plain object

### ISSUE THREAD

**Issue by bhishp** [NicholasPeretti/subforms-example#3]
Just to carry omn the discussion from here (https://github.com/jaredpalmer/formik/issues/826#issuecomment-566054325), so as not to populate the other issue comments.

You give the example:

```js
const rootValidationSchema = yup.shape({
  ...subForm1.validationSchema(),
  ...subForm2.validationSchema().
})
```

I don't think you actually have to do this to get the support you want, you can just use the concat function. https://github.com/jquense/yup#mixedconcatschema-schema

This allows you to concat several schemas together, such as:

```js
const rootValidationSchema = yup.object()
  .concat(subForm1.validationSchema)
  .concat(subForm2.validationSchema);

// (where validationSchemas are of type yup.ObjectSchema)
```

Or, you could even do a mix of top-level and nested schemas

```js
const rootValidationSchema = yup.object({
  aNestedSubFormSchema: subForm3.validationSchema
})
  .concat(subForm1.validationSchema)
  .concat(subForm2.validationSchema);
```

**Comment by NicholasPeretti** [comment]
Wow! I've totally missed that point in the documentation! Thanks! 😄 
Anyhow, I still prefer to export validation schemas as functions, so I can parametrise them and generate schemas dynamically.

What do you think about that @bhishp ? 😄

**Comment by NicholasPeretti** [comment]
@bhishp on seconds thoughts, I think I'll stick with plain objects instead of using the `concat` method from `yup`.

I think that the object allows me to be more flexible - for example I can pick or omit validations from the returned object.
It just seems to me that a plain object is way more flexible than the yup.object, what do you think about it? 🤔
